events { worker_connections 1024; }

http {
    upstream splunk_shc {
        ip_hash;        
        server splunk-sh1:8000;
        server splunk-sh2:8000;
        server splunk-sh3:8000;
    }

    server {
        listen 80;
        server_name splunk_cluster.localhost;

        proxy_buffers 16 16k;
        proxy_buffer_size 32k;

        location / {
            proxy_pass http://splunk_shc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}
